/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

import java.awt.Dialog;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.*;

/**
 * @author 22cri
 */
public class Login extends javax.swing.JFrame {

    // Variables declaration - do not modify                     
    private javax.swing.JTextField emailTxtBox;
    private javax.swing.JLabel enterEmailLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton languageToggle;
    private javax.swing.JButton login_createAcc_Btn;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton viewAllBtn;


    private ResourceBundle bundle;
    private CustomerController customerController;
    // private CustomerController customerController;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);

        //load icon
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/munchFastIcon.png"));
        setIconImage(icon.getImage());
        // Initialize the CustomerController() to handle operations (create, read, delete...)
        customerController = new CustomerController();

        loadLanguage(LanguageControl.getLanguage());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        enterEmailLabel = new javax.swing.JLabel();
        emailTxtBox = new javax.swing.JTextField();
        login_createAcc_Btn = new javax.swing.JButton();
        viewAllBtn = new javax.swing.JButton();
        languageToggle = new javax.swing.JToggleButton();
        logoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Munch Fast !");
        setAlwaysOnTop(true);
        setResizable(false);

        exitButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Welcome To Munch FASTTTT !  Please login or create an account to continue.");
        jLabel2.setToolTipText("");

        enterEmailLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        enterEmailLabel.setText("Enter your email : ");

        login_createAcc_Btn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        login_createAcc_Btn.setText("Login/Create Account");
        login_createAcc_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_createAcc_BtnActionPerformed(evt);
            }
        });

        viewAllBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        viewAllBtn.setText("(ADMIN) View All");
        viewAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllBtnActionPerformed(evt);
            }
        });

        languageToggle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        languageToggle.setText("English");
        languageToggle.setMaximumSize(new java.awt.Dimension(76, 36));
        languageToggle.setMinimumSize(new java.awt.Dimension(76, 36));
        languageToggle.setPreferredSize(new java.awt.Dimension(76, 36));
        languageToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageToggleActionPerformed(evt);
            }
        });

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/munchFastLogoSmall.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(exitButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(viewAllBtn))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(languageToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(163, 163, 163)
                                                .addComponent(logoLabel)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(enterEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)
                                                .addComponent(emailTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(login_createAcc_Btn)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(languageToggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(logoLabel)))
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(enterEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(login_createAcc_Btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(exitButton)
                                        .addComponent(viewAllBtn))
                                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //terminates application
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    //if email doesnt exist in db, then take to create a user
    private void login_createAcc_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_createAcc_BtnActionPerformed
        if (!emailTxtBox.getText().isEmpty()) {
            //get client list from model
            List<Customer> clients = customerController.getAllCustomers();
            //go through list and compare the text to the email data member
            for (Customer c : clients) {
                if (c.getEmail().equals(emailTxtBox.getText())) {
                    // if found then open new form and dispose this one (add a confirmation message
                    JOptionPane.showMessageDialog(this, "Welcome back!");
                    new MainMenu(customerController.getCustomerByEmail(emailTxtBox.getText())).setVisible(true);
                    this.dispose();
                }
            }
            new CreateUserForm().setVisible(true);
            this.dispose();
            return;
        }
        JOptionPane.showMessageDialog(this, "Nothing to login/create");
        emailTxtBox.setText("");
    }//GEN-LAST:event_login_createAcc_BtnActionPerformed

    //admin method to view whats going on in database
    private void viewAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllBtnActionPerformed
        JTextArea textArea = new JTextArea(10, 30); // 10 rows, 30 columns
        textArea.setText("WILL BE ADDED LATER");
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setEditable(false); // Make the text area read-only           

        JScrollPane scrollPane = new JScrollPane(textArea);

        JOptionPane optionPane = new JOptionPane(
                scrollPane,
                JOptionPane.INFORMATION_MESSAGE,
                JOptionPane.DEFAULT_OPTION);

        JDialog dialog = optionPane.createDialog("Database Information");
        dialog.setModalityType(Dialog.ModalityType.MODELESS);
        dialog.setSize(700, 500);
        dialog.setLocation(50, 50);
        dialog.setResizable(true);

        dialog.setVisible(true);
    }//GEN-LAST:event_viewAllBtnActionPerformed

    //method to load language on components
    private void loadLanguage(String language) {
        //set with language class
        LanguageControl.setLanguage(language);
        //load bundle
        bundle = ResourceBundle.getBundle("language", LanguageControl.getCurrentLocale());

        //update UI
        exitButton.setText(bundle.getString("exit"));
        login_createAcc_Btn.setText(bundle.getString("loginCreate"));
        jLabel2.setText(bundle.getString("welcome"));
        enterEmailLabel.setText(bundle.getString("email"));
    }


    //change language
    private void languageToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageToggleActionPerformed
        if (languageToggle.isSelected()) {
            loadLanguage(("fr"));
            languageToggle.setText("English");
        } else {
            loadLanguage("en");
            languageToggle.setText("French");
        }
    }//GEN-LAST:event_languageToggleActionPerformed
    // End of variables declaration                   
}
